from django.urls import path
from Backend import views

urlpatterns = [
    path('indexpage/', views.indexpage, name='indexpage'),
    path('register/', views.register, name='register'),
    path('AdminLoginPage/', views.AdminLoginPage, name='AdminLoginPage'),
    path('AdminLogin/', views.AdminLogin, name='AdminLogin'),
    path('otp_verification/', views.otp_verification, name='otp_verification'),
    path('AdminLogout/', views.AdminLogout, name='AdminLogout'),
    # *********************************************************************************
    # email_verification
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset_password'),
    # path('password_rest_sent/', auth_views.PasswordResetDoneView.as_view(), name='repassword_reset_sent'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_rest_complete/', views.CustomPasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
    # *********************************************************************************
    path('AddAccounts/', views.AddAccounts, name='AddAccounts'),
    path('accountssave/', views.accountssave, name='accountssave'),
    path('displayAccount/', views.displayAccount, name='displayAccount'),
    path('editaccount/<int:accid>/', views.editaccount, name='editaccount'),
    path('updateaccount/<int:accid>/', views.updateaccount, name='updateaccount'),
    path('deleteaccount/<int:accid>/', views.deleteaccount, name='deleteaccount'),
    path('addaccounttype/', views.addaccounttype, name='addaccounttype'),
    path('typesave/', views.typesave, name='typesave'),
    path('displayaccounttype/', views.displayaccounttype, name='displayaccounttype'),
    path('editaccounttype/<int:typeid>/', views.editaccounttype, name='editaccounttype'),
    path('typeupdate/<int:typeid>/', views.typeupdate, name='typeupdate'),
    path('deleteaccounttype/<int:typeid>/', views.deleteaccounttype, name='deleteaccounttype'),
    path('PendingAccountDisplay/', views.PendingAccountDisplay, name='PendingAccountDisplay'),
    path('approved_accounts/', views.approved_accounts, name='approved_accounts'),
    path('deletecustomeraccount/<int:accid>/', views.deletecustomeraccount, name='deletecustomeraccount'),
    path('approvecustomer/<int:accid>/', views.approvecustomer, name='approvecustomer'),
    path('approve_account/<int:accid>/', views.approve_account, name='approve_account'),
    path('blocked_accounts/', views.blocked_accounts, name='blocked_accounts'),
    path('unblock/', views.unblock, name='unblock'),
    path('add_loan/', views.add_loan, name='add_loan'),
    path('save_loan/', views.save_loan, name='save_loan'),
    path('loan_display/', views.loan_display, name='loan_display'),
    path('loan_edit/<int:loan_id>/', views.loan_edit, name='loan_edit'),
    path('update_loan/<int:loan_id>/', views.update_loan, name='update_loan'),
    path('delete_loan/<int:loan_id>/', views.delete_loan, name='delete_loan'),
    path('approved_loans/', views.approved_loans, name='approved_loans'),
    path('pending_loans/', views.pending_loans, name='pending_loans'),
    path('delete_userloan/<int:loanid>/', views.delete_userloan, name='delete_userloan'),
    path('loan_sanction/<int:loanid>', views.loan_sanction, name='loan_sanction'),
    path('approve_loan/<int:loanid>/', views.approve_loan, name='approve_loan'),
    path('customer_review_display/', views.customer_review_display, name='customer_review_display'),
    path('delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('addnews/', views.addnews, name='addnews'),
    path('save_news/', views.save_news, name='save_news'),
    path('display_news/', views.display_news, name='display_news'),
    path('edit_news/<int:news_id>/', views.edit_news, name='edit_news'),
    path('update_news/<int:news_id>/', views.update_news, name='update_news'),
    path('delete_news/<int:news_id>/', views.delete_news, name='delete_news'),
    path('customer_messages_display/', views.customer_messages_display, name='customer_messages_display'),
    path('delete_messages/<int:message_id>/', views.delete_messages, name='delete_messages'),
]