# Generated by Django 5.0.1 on 2024-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('MOBILE', models.TextField(blank=True, max_length=100, null=True)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('ADDRESS', models.TextField(blank=True, max_length=600, null=True)),
                ('CITY', models.TextField(blank=True, max_length=100, null=True)),
                ('STATE', models.TextField(blank=True, max_length=100, null=True)),
                ('COUNTRY', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
