# Generated by Django 5.0.1 on 2024-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_accountcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='AADHAR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountcreation',
            name='CITY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountcreation',
            name='COUNTRY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountcreation',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountcreation',
            name='STATE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
