# Generated by Django 5.0.1 on 2024-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_accountcreation_aadhar_alter_accountcreation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
