# Generated by Django 5.0.1 on 2024-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_accountcreation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='ACCNO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountcreation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
