# Generated by Django 5.0.1 on 2024-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_accountcreation_accno_accountcreation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
