# Generated by Django 5.0.1 on 2024-01-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_accountcreation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcreation',
            old_name='NAME',
            new_name='USERNAME',
        ),
    ]
