# Generated by Django 5.0.1 on 2024-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_accountcreation_customerid'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='accountCreationDB',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('CUSTOMERID', models.IntegerField(blank=True, null=True)),
        #         ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
        #         ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
        #         ('ACCTYPE', models.CharField(blank=True, max_length=100, null=True)),
        #         ('ACCNO', models.CharField(blank=True, max_length=100, null=True)),
        #         ('MINBALANCE', models.IntegerField(blank=True, null=True)),
        #         ('AADHAR', models.CharField(blank=True, max_length=100, null=True)),
        #         ('MOBILE', models.CharField(blank=True, max_length=100, null=True)),
        #         ('DATE', models.DateField(blank=True, null=True)),
        #         ('ADDRESS', models.TextField(blank=True, max_length=600, null=True)),
        #         ('CITY', models.CharField(blank=True, max_length=100, null=True)),
        #         ('STATE', models.CharField(blank=True, max_length=100, null=True)),
        #         ('COUNTRY', models.CharField(blank=True, max_length=100, null=True)),
        #         ('IMAGE', models.ImageField(blank=True, null=True, upload_to='Images')),
        #         ('status', models.CharField(blank=True, max_length=100, null=True)),
        #     ],
        # ),
    ]
