# Generated by Django 5.0.1 on 2024-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_transactionhistory_userregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=200, null=True)),
                ('MOBILE', models.CharField(blank=True, max_length=200, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=600, null=True)),
                ('AADHAR', models.CharField(blank=True, max_length=200, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('PROFILEMAGE', models.ImageField(blank=True, upload_to='Images', null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
