# Generated by Django 5.0.1 on 2024-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_accountcreationdb_transactionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('CUSTOMERID', models.IntegerField(blank=True, null=True)),
                ('sender_accno', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_accno', models.CharField(blank=True, max_length=100, null=True)),
                ('transfertype', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_transferred', models.IntegerField(blank=True, null=True)),
                ('balance_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
