# Generated by Django 5.0.1 on 2024-01-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_accountcreationdb_transactionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSanctionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMERID', models.IntegerField(blank=True, null=True)),
                ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('LOANTYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('ACCNO', models.CharField(blank=True, max_length=100, null=True)),
                ('BALANCE', models.IntegerField(blank=True, null=True)),
                ('AADHAR', models.CharField(blank=True, max_length=100, null=True)),
                ('MOBILE', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('IMAGE2', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('loanamount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRatingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userregistrationdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reviewratingdb',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.userregistrationdb'),
        ),
    ]
