# Generated by Django 3.1.8 on 2024-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('ACCDESC', models.CharField(blank=True, max_length=100, null=True)),
                ('ACCIMAGE', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
