# Generated by Django 3.1.8 on 2024-01-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_accountdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdb',
            name='ACCFULLDESC',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
