# Generated by Django 3.1.8 on 2024-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_accountdb_accfulldesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdb',
            name='ACCFULLDESC',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
