# Generated by Django 3.1.8 on 2024-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20240109_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT', models.CharField(blank=True, max_length=100, null=True)),
                ('ACCOUNTTYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('SHORTDESC', models.CharField(blank=True, max_length=800, null=True)),
                ('FULLDESC', models.CharField(blank=True, max_length=3000, null=True)),
                ('TYPEIMAGE', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
