# Generated by Django 5.0.1 on 2024-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_accountdb_id_alter_accounttypedb_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
