# Generated by Django 5.0.1 on 2024-02-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_loandb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('full_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
